### ISSUE TITLE
Transition missing for shadow

### ISSUE THREAD

**Issue by facadev** [timurnurutdinov/Framer-Inventory#27]
Two artboards, one rectangle. If you assign a drop-shadow property to the second one and export it with states, you will find that the base state of the rectangle has no shadow property in it, causing the transition to look quite quirky. To fix the problem, you have to either add a drop-shadow property to the rectangle in the first artboard, or add the property yourself in the output code.

I think that is a general problem, and the plugin should first collect all the properties that are used across different artboards. When exporting, it should automatically add missing properties with default values (eg. in this case, it should add "zero shadow" to the base state so that Framer knows there should be a transition). 

BTW, 1. Is there a way to export gradient as also, or to force an oval with gradient to be exported as an image? And is there a way to export text and images? 2. The plugin should also check for invalid names of layers or rename them automatically (eg. "-" is not a valid character in Javascript variables, maybe it can change such punctuations into an underscore).

Anyway, I really love this plugin. It shows Framer & Sketch 's real potential in prototyping.

Edit: Uh, found a workaround! Seems that I have to group an object to make the plugin able to detect it as an asset. And that seems to be the only way to export text. ("Replicate Selected" will tell you the text layer has been exported, whereas it only adds a "}" add the end of the code... I guess it's a bug here. :) )

**Comment by timurnurutdinov** [comment]
1. Shadows bug: confirmed.
   Please, can you share .sketch file? Because I noticed strange Framer behaviour -  shadows are animatable in one direction even if I use default values: http://share.framerjs.com/20dakieog993/
2. Gradient / Text
   Exportable as images (should be placed in a group)
3. Invalid names
   Naming should be improved but you'd better create another issue for that one, because it should replace leading numbers/symbols and much more. 

P.S. Thanks for helping me making a plugin better. But for better collaborating I suggest you to create multiple issues instead of one :)

**Comment by facadev** [comment]
Sure. Next time will be... :100:
