### ISSUE TITLE
Image path not resolved properly

### ISSUE THREAD

**Issue by facadev** [timurnurutdinov/Framer-Inventory#28]
A component named "Bar / Navigation" in the output code would be pointed to "images/ Navigation.png", which is incorrect.

**Comment by timurnurutdinov** [comment]
Confirmed. 

Have just updated master. Please, take your time to test it.

**Comment by facadev** [comment]
So efficient. :+1:  :)

**Comment by irenalin** [comment]
I'm having the same problem.  Been scratching my head all day.  A bunch of the rectangles and ovals on sketch are being exported as images

I think I understand now.  So if I want the shape to be exported as a shape, I should not group it and export the group.  Exporting a group will export as an image, however, this only seems to work when using drag/drop.  When I try to export a group with this plugin, it attempts to create an image, which is not rendering.  I don't know if the image was created correctly...it's showing up as a new layer and it's positioned, just no picture rendered.  Also, are text elements from sketch exportable, I can't get that to work either

**Comment by timurnurutdinov** [comment]
Plugin was supposed to work with groups only. Because of a lot of reasons: hard to replicate gradients, multiple shadows/borders, texts need fonts and a lot more, multiple nested masks are tricky.

But I realise that for rectangles and ovals with solid colours it's nice to have an ability to export them without an image (just for fast prototyping reasons!). Currently I have no plans to expand shapes support so I will update description soon!

**Comment by irenalin** [comment]
Interesting.  I checked out http://timurnurutdinov.github.io/framerinventory/ and went to Examples and found this file 'framer-inventory-shapes-example.zip', which doesn't have groups for all the exportable and animatable objects.  If you look at the first few artboards, the 'square' is not marked as exportable, nor is it grouped.  Is there a limit on how many layers I can export?  I'm also confused as to when I should mark a layer as exportable...because the example is not exactly consistent in marking layers as exportable either...some layers have it on one artboard but then don't have it on another artboard....

I hate to take up your time, but this would really become a valuable tool for our design team, so I really want to figure this one out.  Thanks!!

**Comment by timurnurutdinov** [comment]
I'd like to say a big thank you for you using the plugin and asking all these questions. I understand that I should better explain the basics of logic and current flow (have great plans for future, hope will have time this or next week!). 

Unlimited amount of  layers (groups) can be exported. Just one condition: they should have unique names! Then you mark a layer as exportable, you are just saying to plugin that you would like to include this object (plugin gets name of the object and then look for states on all artboards). So it doesn't matter how many times you mark exportable layers with one name - plugin doesn't allow dublicates (because objects with the same name from different artboards are the same object but with different states). If there is no object, plugin tries to "help" you :)

BUT! Searching layers in Sketch document uses the same sequence as you do for scenario (from bottom layers in Layer View and then search goes up). So marking as exportable matters for hierarchy of layers in the generated prototype! I've attached a png to help you understand this (3 examples).
![preview](https://cloud.githubusercontent.com/assets/3430880/10174406/547481c0-66f2-11e5-911c-854d01f5b690.png)

And again, appreciate your help with testing and all other stuff! If you have some cases you'd like to be possible with plugin, you are welcome! Because I use plugin on a daily basis but still think it can be much more useful product!
