### ISSUE TITLE
Can't export masks, text and images

### ISSUE THREAD

**Issue by marshmiller** [timurnurutdinov/Framer-Inventory#31]
I love this plugin but it looks like I can't pull masks, images, or text into Framer Studio :(

Masks appear as regular shapes but text or images won't show up in the previewer! 

It would so awesome if this plugin would allow that. Unless this is a bug or functionality to be added later on? 

Thank you so much for creating this!

**Comment by timurnurutdinov** [comment]
It's nice to see you use the plugin! Let me explain current situation:
1. Images
   In current version you can't export image itself. You should group it to be exportable. Had done it for some technical reasons but lately found it inconvenient. Will definitely add this functionality in version 1.1
2. Masks
   Custom masks can be tricky (?) but rectangle masks will be in version 1.1. I don't know exactly about nested masks but one mask per group is a must-have ^^
3. Texts
   Grouped texts can be exported as images. I haven't yet made a deep exploration in this area but it doesn't seem to be a priority right now. (If you can explain benefits from having texts instead of images, I can add this in TODO list)

Using Framer Inventory on a daily basis, so looking forward to get version 1.1 as well :)
