### ISSUE TITLE
Many bugs please fix

### ISSUE THREAD

**Issue by LiTiang** [timurnurutdinov/Framer-Inventory#46]
Hi, great work
i really love this plugin u made, 
but it seems like many bugs also

#### i really want to buy this plugin to support u ❗️❗️❗️
but i cant because too many bugs at now
hope u can fix that as soon as possible

---

* OS X EI Capitan v10.11.1
* Sketch v43.2
* Framer Inventory v3.0.1

---
I follow your video tutorial, 
i also download the files which related to that tutorial 
> i.e. 
> * Uber with Framer Inventory.framer
> * framer-inventory-3-uber-example.sketch

but i have no idea why i cant do the same things which u do in that video 
#### u can see the details in my [video](https://youtu.be/eF21QiaS-y8) ❗️❗️❗️

e.g. bug1
---
I copy the layer - `card_content` in Artboard - `uber/map`, 
and i paste that code in **_Framer_**, but the y position of `card_content` is wrong !!

e.g. bug2
---
i copy the layer - `card bg` of Artboard - `uber/map` & `uber/ride`
after i paste the code in **_Framer_**, i get the below . . .
```
card_content = new Layer
	width: 1312
	height: 1200
	x: 64
	y: 2292
	image: "images/card content.png"
	style: {"-webkit-filter": "drop-shadow(0px 0px 80px rgba(0,0,0,0.3))"}

card_bg = new Layer
	width: 1440
	height: 1920
	x: 0
	y: 0
	backgroundColor: "rgba(1,0,204,0.5)"
```

e.g. . . .
---

**Comment by timurnurutdinov** [comment]
Hi LiTang,

I've checked your video and can say that everything works as expected. Let me explain:

1. You got "y: 240" because you prototype for Nexus 6P. It means everything should be scaled x4 to be properly viewed in Framer (Nexus 6P has 360*4 = 1440px wide screen and you have 360 pt wide artboards in Sketch). Now you can ask why you got 240px (=60pt) when you have it much more in Sketch? It's because you switched relative to group coordinates option in plugin (blue icon on the top right) – switch it off and everything will work as expected ;)

2. If you'd like to generate states but there are no changes, you'll get just layers. It's connected to my answer to №1, just switch relative to group option off and you'll get differences!

Hope it will help you to get the main concept of Framer Inventory and the next uses will be a breeze :)

**Comment by LiTiang** [comment]
@timurnurutdinov, thx reply, 

---

i now try this plugin all functions again
and i still find the problem
i will collect all my Questions as soon as possible

#### P.S. 
this plugin is really awesome ❗️
and it will change my workflow❗️❗️

Thank u  ❤️

**Comment by LiTiang** [comment]
Hi, @timurnurutdinov, may be i'm so stupid, 

but it really hard for me to try to gain the knowledge from u video

i think one of the reasons is . . .

the process in that video is not PURELY step by step

so i feeling confuse many times when i look of it
( Hope u know what i said )  

> but i know this plugin definitely powerful ❗️❗️❗️

plz forgive me that i'm now post my **first group Questions** 
( it's about u **Import States Video** )

and plz answer me 😳, plz plz plz

---
#### Q1 - i cant re-produce card_content.parent = card_bg

i do the same thing as u do in video . . .

check this 

https://youtu.be/H_SIedCDdtU

#### Q2 - Why different operations on layers arrow_back & darker ?

> at 01:32 in u Video

In u **_Sketch_** file, there're only layer : `arrow_back` in **Artboard** `uber/ride`

but i saw u already have the definition `arrow_back.states = . . .`, how u do that ?

If that code was produced by this plugin, then i dont know how to re-produce it

if that code is just u type it in **_Framer_**, then the next question is :

why dont u insert the same layer in **Artboard** `uber/map` with opacity 0,

and select both layers, click the plugin button - `Selected States of Layers` ?

#### Q3 - The confuse options on Plugin Interface

if i select layer: `arrow back` in **_Sketch_**,

and i see there're two options appear on Plugin,

* `Layer`
* `States on Page`

i use each one, and i dont see any different between them,

so in this case, why `States on Page` need to be exist ?

#### Q4 - What the " Iterations " meaning ?

> at 02:24 in u Video

The Video section title is **Iterations with Copy-Paste**

i know u copy both **Artboard** and paste in somewhere,

so . . . what the relationship wth this action and the noun " Iterations " ?

also, i have no idea -

how do u drag `card_content` to the top and both layers `where` & `icon` also transition to the top sync ?

**Comment by timurnurutdinov** [comment]
Hi again,

You are correct, it's not a tutorial video, it's just a demo of how to use the plugin with a real life example. Tutorials are boring and almost nobody would watch them to the end. So let me explain some details:

A1: You have to add "layerA.parent = layerB" code by yourself. Why? At this time I think it's more secure because you import only layerA and plugin can't predict the parent name (ex. you can create a scroll component with code and want to add a content with plugin).

A2: How did I generated the states for arrow? It's an easy answer. You've got "more" button on the right bottom side of the panel and you can select a layer and generate "Shown/Hidden" states. It just makes opacity 0/1 states, because I reckon nobody likes creating hidden layers on artboards ^^

A3: "Layer" gets code for this layer only. "States for page" means plugin will take a look for entire page (= all artboards) and generate available states if there are some differences. If not, the result will be the same. Pro tip: select layer and some artboards to generate states for selected range.

A4: With Framer Inventory you can get states and write additional logic on the top of this. In this section of the video I've shown that you can change something on artboards and reimport to update visuals in your prototype – there are iterations, the way you provide the best solution possible.
The movement of the elements is synced the way it depends on states and it's a custom block of logic written (you can download Framer project to take a look at it). It's really where to show that the states are not just animations but controllable transitions to be created with Framer Inventory.


P.S. Thank you for your questions, really appreciate your enthusiasm. Thinking about posting an article with a deeper look at all this stuff. Also I suggest to think about principles of Framer Inventory rather then of just certain examples because every prototype is unique and sometimes you can get almost everything with Framer Inventory and for some – a little (ex. it you generate patterns or populate data). Feel free to ask any feather questions!

Best wishes!

**Comment by LiTiang** [comment]
### plz forgive me i will make questions on my **first group Questions** again

---

#### A1
i saw u paste the **_framer_** code in Video, 
and that logic ( `layerA.parent = layerB` ) was generated automatically, 
but now, as u said, at least in this version of the plugin, we need to add that logic by ourself

anyway

u still point out the important concept in Video, 
that's, if we use **" mask "** in **_Sketch_**, 
we should check if we need to add the parent-child logic in **_Framer_** after we paste the code

#### A2
sorry, i try my best to understand u reply, 
but i still dont know what are u talking about - 

( "more" button ? what's that ? )

```
You've got "more" button on the right bottom side of the panel and you can select a layer and generate "Shown/Hidden" states.
```

but i totally understand your consideration : 
```
I reckon nobody likes creating hidden layers on artboards
```

#### A3
i just think why dont u hide the plugin option `States on Page` ?
because i just select one layer, and the option `States on Page` will be meaningful ONLY when i select the same layers in different **Artboards**, right ?

#### A4
OK, so u created a vocabulary called `iterations`, 
that mean : we can do more thing ( i.e. add additional logic by ourself ) on **Artboards**,
and u show how to do that by copy the **Artboards**, 
move the layer: `where` over the Artboard boundary, 
and paste such code in **_Framer_** . . . 

and this procedure is called `iteration`, right ?

**Comment by timurnurutdinov** [comment]
Hi,

I'm on a vacation this week so replying with a delay. 

A2: https://www.dropbox.com/s/h7c762jws0vd4el/more%20options.mov?dl=0
A3: No, it's not. If you have several artboards and all of them to be included in prototype – this option will be very handy.
A4: I was talking about something like this: https://en.wikipedia.org/wiki/Iterative_design So usually just one prototype is nothing, and you have to iterate with various designs/logic/etc. That's why I show in video how you can "update" prototype by changing something on artboards.

**Comment by LiTiang** [comment]
@timurnurutdinov, Great reply 😍
Now i totally understand what u said ❗️

BTW, 
u give me a great lesson of "Iteration Design", THX
> Iterative design is a design methodology based on a cyclic process of prototyping, testing, analyzing, and refining a product or process.

**Comment by LiTiang** [comment]
Below are final questions collection
About - **Import States V.S. Export Prototype**


---

>

by studying u video, i know that . . .

if we use **Import States**, we got that layer in **_Framer_**

if we use **Export Prototype**, 

we got the layer with animation code( i.e. `cycleButton` ) in **_Framer_**

#### Q1 - Why naming the feature as Export Prototype ?
---
because the auto-generated animation code

i think that's is why u call that feature - **Export Prototype**

right ?

---
By comparing with **Import States** & **Export Prototype**

we MAY want to use **Import States** with enabled button(the blue color one): `Folder`,

if we find out . . .

* There're mask operation on some layers

* Some layers are in the so called container layer

and if we need to get animation code, we need to use **Export Prototype**

#### Q2 - Can u provide more clear difference between such 2 features ?
---
or if u think what i said above is clear enough . . .

**Comment by timurnurutdinov** [comment]
Hi again,
I'm finally back from my vacation!

The question behind 2 actions is quite tricky. Two years ago I created a quick plugin to export only layers but that wasn't interesting for me. So I added support for states. Then I realised than create lots of prototypes with the same logic similar to presentation in a Keynote. How to use them is up to you. Usually I start with **Export Prototype** feature and test a couple of approaches and then create something more complex with the help of **Import States**.

I'm closing the thread because it's not about bug fixing anymore. If you want to chat about plugin more, you can ping me in twitter @framerinventory or send email at framerinventory@gmail.com (any of these ways are more convenient than Github threads, I think)

**Comment by LiTiang** [comment]
HI, @timurnurutdinov, thanks reply

You really give a great answers !

I totally understand u plugin now !

thanks again
